name: lmopticos

services:
  postgres:
    image: postgres:18.4
    container_name: lmopticos-postgres
    environment:
      POSTGRES_DB: lmopticos
      POSTGRES_USER: lmopticos_user
      POSTGRES_PASSWORD: lmopticos_pass
    ports:
      - "5432:5432"
    volumes:
      - lmopticos-pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  lmopticos-pgdata:
